INHERIT: mkdocs-base.yaml

site_name: "My Bindplane"
repo_name: "View Code on GitHub"
repo_url: "https://github.com/dynatrace-wwse/enablement-bindplane-logs"
nav:
  - "1. About": index.md
  - "2. Getting started": 2-getting-started.md
  - "3. Installing the Bindplane Agent": 3-bindplane-agent.md
  - "4. Bindplane Configuration": 4-bindplane-configuration.md
  - "5. Processors: Add a Field": 5-add-field.md
  - "6. Parsing with OpenPipeline": 6-parsing-with-openpipeline.md
  - "7. Masking Data & Routing": 7-masking-routing.md
  - "8. Extracting Metrics from Logs": 8-metric-extraction.md
  - "9. Bindplane Health": 9-bindplane-health.md

extra:
  rum_snippet: "https://js-cdn.dynatrace.com/jstag/1612cf70810/bf81393wlb/7beb0d47dc2924d4_complete.js"
